Repository aritroCoder/IITP-Gymkhana, pull requests merged in 2022-12, with the labels that each got.

#10 Removed Carousel
  index.html
Labels: points:1, codepeak 22

#11 added know more button
  css/style.css
  index.html
Labels: codepeak 22, points:5

#12 council carousel added
  index.html
  socities-carousel/carousel.css
  socities-carousel/carousel.js
Labels: points:10
